---
# Setup/install tasks.
 
- name: "Include Red Hat tasks if distribution is Red Hat"
  ansible.builtin.include_tasks:
    file: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Fedora'

